# Generated by Django 6.0.1 on 2026-06-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345, max_length=100, verbose_name='password'),
            preserve_default=False,
        ),
    ]
