# Generated by Django 6.0.6 on 2026-06-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Tareas',
        ),
    ]
