# Generated by Django 6.0.6 on 2026-06-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_rename_tarea_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('abierta', 'Respuesta abierta'), ('opcion_multiple', 'Opción múltiple')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('recurso_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='tareas.tareas')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='tareas.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('imagen', 'Imagen'), ('documento', 'Documento'), ('url', 'URL')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actividades/')),
                ('url', models.URLField(blank=True, null=True)),
                ('recurso_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='tareas.tareas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.pregunta')),
            ],
        ),
    ]
