# Generated by Django 6.0.1 on 2026-06-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_tareas_fecha_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecursoTareas',
        ),
    ]
