# Generated by Django 6.0.1 on 2026-06-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_delete_recursotareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='URL del video'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_entrega',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
