# Generated by Django 6.0.1 on 2026-06-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_tareas_url_video_alter_tareas_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='url_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
