# Generated by Django 6.0.1 on 2026-06-10 03:45

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_tareas_fecha_entrega_alter_tareas_url_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='url_video',
        ),
        migrations.AddField(
            model_name='tareas',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=12345),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
