# Generated by Django 6.0.1 on 2026-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
