# Generated by Django 6.0.1 on 2026-06-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_alter_tareas_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
