# Generated by Django 6.0.1 on 2026-06-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_alter_tareas_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
