# Generated by Django 6.0.1 on 2026-06-10 23:22

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0013_alter_tareas_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
