# Generated by Django 6.0.1 on 2026-06-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_alter_tareas_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpcionRespuesta',
            new_name='Opcion',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='recurso_tarea',
            new_name='tarea',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='orden',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('texto', 'Respuesta Abierta')], max_length=20),
        ),
        migrations.CreateModel(
            name='RespuestaCorrecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tareas.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
