# Generated by Django 6.0.1 on 2026-06-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0015_rename_opcionrespuesta_opcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Respuesta abierta'), ('opcion', 'Opción múltiple')], max_length=20),
        ),
    ]
