# Generated by Django 6.0.1 on 2026-06-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0016_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='puntaje',
            field=models.IntegerField(default=1),
        ),
    ]
